# 필터링 옵션 설정
# 영화 기반 추천에서 사용하는 장르, 언어 설정

genres:
- SF
- TV
- 가족
- 공포
- 다큐멘터리
- 드라마
- 로맨스
- 모험
- 미스터리
- 범죄
- 서부
- 스릴러
- 애니메이션
- 액션
- 역사
- 영화
- 음악
- 전쟁
- 코미디
- 판타지

languages:
- 영어
- 한국어
- 중국어
- 일본어
- 독일어
- 러시아어
- 베트남어
- 스페인어
- 인도네시아어
- 터키어
- 프랑스어
- 이탈리아어